### ISSUE TITLE
Use `vi` renderer rather than `json` for module requests

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-vuevi#3]
It seems that the new VI expects all modules to have `Module.json = True` set, as the `json` renderer seems to be used. This should be changed to the `vi` renderer as in previous VI versions.
![image](https://user-images.githubusercontent.com/16870072/232481819-696a2741-c601-4f44-a053-c840bb886b50.png)

**Comment by ArneGudermann** [comment]
I think the problem is in https://github.com/viur-framework/viur-vue-utils/blob/main/packages/viur-vue-utils/utils/request.js because this alway use the json Renderer.

**Comment by phorward** [comment]
> I think the problem is in https://github.com/viur-framework/viur-vue-utils/blob/main/packages/viur-vue-utils/utils/request.js because this alway use the json Renderer.

Maybe. This should be parametrizable in viur-vue-utils and default to `vi` in VI 4.0.0.
